PHP 8.2 integration tests: Remove experimental flag
Parsely/wp-parsely pull request #1697
Opened 2023-07-04 07:06 UTC by acicovic

## Description
This PR moves code coverage from PHP 8.0 to PHP 8.1 for our integration tests.

## Motivation and context
Move code coverage to a more recent PHP version.

## How has this been tested?
Re-running existing tests and seeing that code coverage is now present in PHP 8.1.

2023-07-04 08:42 UTC, mehmoodak requested changes

2023-07-04 08:42 UTC, mehmoodak commented on .github/workflows/integration-tests.yml
Any changes in `unit-tests.yml` file?

2023-07-04 12:09 UTC, acicovic commented on .github/workflows/integration-tests.yml
Updated `unit-tests.yml`!

2023-07-10 18:52 UTC, mjangda approved these changes

2023-07-10 18:52 UTC, mjangda commented on .github/workflows/unit-tests.yml
>            # Separate out PHP 8.0, so it can run with code coverage.
```suggestion
          # Run code coverage for only one PHP version
```

2023-07-11 06:00 UTC, merged