Change $post to $parsely_type
Parsely/wp-parsely pull request #271
Opened 2021-05-03 09:28 UTC by htdat

Fix #245

There is no major change in this PR. 

Instead, I reviewed the code: 

- [x] This method `get_current_url` is being used in the same class and only in this method `construct_parsely_metadata`. - [ref line](http://github.com/Parsely/wp-parsely/blob/73b0726dc6f2cdd178e9f348514a23ab8ab74253/src/class-parsely.php#L827-L827)
- [x] It is used in `class-all-test.php` file to test itself. I checked and there is no need to change anything also - [ref line](http://github.com/Parsely/wp-parsely/blob/73b0726dc6f2cdd178e9f348514a23ab8ab74253/tests/class-all-test.php#L792-L792).  
- [x] Unit tests are passed.

2021-05-03 19:58 UTC, GaryJones requested changes

2021-05-03 19:58 UTC, GaryJones commented on src/class-parsely.php
> +	 * @param int    $post_id      id of the post you want to get the url for. Optional.
```suggestion
	 * @param int    $post_id      Optional. ID of the post you want to get the URL for. Default is 0, which means the global `$post` is used.
```

2021-05-03 19:58 UTC, GaryJones commented on src/class-parsely.php
> +	 * @param string $parsely_type Parsely post type you're interested in, either "post" or "nonpost"
```suggestion
	 * @param string $parsely_type Optional. Parse.ly post type you're interested in, either 'post' or 'nonpost'. Default is 'nonpost'.
```

2021-05-03 19:58 UTC, GaryJones commented on src/class-parsely.php
> +			 * @param string $parsely_type      Parsely type ("post" or "nonpost").
```suggestion
			 * @param string $parsely_type      Parse.ly type ("post" or "nonpost").
```

2021-05-03 20:01 UTC, GaryJones approved these changes

2021-05-03 20:01 UTC, merged

2021-05-04 02:27 UTC, htdat commented
Thanks @GaryJones for your review and update.