Add telemetry backend
Parsely/wp-parsely pull request #393
Opened 2021-09-22 09:45 UTC by pauarge

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-10-11 10:45 UTC, GaryJones requested changes
I think some different architecture here will be beneficial. Think about if we had to use a different telemetry system (or consider a `NullTelemetry` class, which would allow events to be registered and recorded, even if it wasn't actually sent anywhere) - what changes would need to be made to the other classes to support this?

2021-10-11 10:45 UTC, GaryJones commented on src/telemetry/class-parsely-a8c-tracks-event.php
> +class Parsely_A8c_Tracks_Event {
Let's use a `Parsely\Telemetry` namespace with an unprefixed class name like `A8c_Tracks_Event` (and similar), for these new classes.

2021-10-11 10:45 UTC, GaryJones commented on src/telemetry/class-parsely-telemetry.php
> +		$this->tracks = new Parsely_A8c_Tracks();
This highly couples the telemetry system to using the Tracks implementation - that means other systems (including mocks for tests) can't be used.

Use constructor dependency injection, type hinted at an interface, here instead.

Roughly (but you can think of better names):

```php
interface Telemetry_System {
	public function setup();
	public function record_event();
}
```

```php
class A8c_Tracks implements Telemetry_System {
	...
}
```

```php
class Telemetry {
	private $telemetry_system;

	public function __construct( Telemetry_System $telemetry_system ) {
		$this->telemetry_system = $telemetry_system;
	}
	...
}
```

```php
// At the point of instantiating Telemetry(), pass in an instance of the desired telemetry system (which at the moment, is only A8c_Tracks):
if ( apply_filters( 'wp_parsely_enable_telemetry_backend', false ) ) {
	$telemetry_system = apply_filters( 'wp_parsely_telemetry_system', new A8c_Tracks() );
	$this->telemetry = new \Parsely\Telemetry\Telemetry( $telemetry_system );
}
```

Now, folks have the ability to use a different system that extend our interface, and we can insert mocks to test the `Telemetry` class without assuming that the implementation is the 
A8c_Tracks.

2021-10-11 10:45 UTC, GaryJones commented on src/telemetry/class-parsely-telemetry.php
> +	protected function add_event_tracking(): void {
It feels like this list of events should be held outside of this class, and registered to the class with a `register_event()` or `add_event()` method.

That would give more flexibility in being able to add extra events for testing, and allow others to add new events to be tracked, and better follows the Single Responsibility Principle.


Simplified: 
```php
// Create new telemetry dispatcher with an instance of the system to use:
$telemetry = new Telemetry( new A8c_Tracks() );

// Now register action and filter hooks and their callbacks.
$telemetry->register_event(
	new Telemetry_Event_Action (
		'my_action_hook',
		'my_callable'
	)
);
$telemetry->register_event(
	new Telemetry_Event_Filter (
		'my_filter_hook',
		'my_callable',
		'my_priority',
		'my_args_count'
	)
);
```

A `$events` property inside Telemetry now contains an array/collection of Telemetry_Event_* data objects.

2021-10-12 08:40 UTC, pauarge commented
Closing this PR because we are implementing the tracking on the VIP side. https://github.com/Automattic/vip-go-mu-plugins/pull/2500

2021-10-12 08:40 UTC, closed without merging