Constant return type on insert_parsely_page
Parsely/wp-parsely pull request #443
Opened 2021-10-11 08:38 UTC by pauarge

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-10-11 09:56 UTC, GaryJones commented on src/class-parsely.php
> -		return $parsely_page;
This is a breaking change - some customers may be expecting the values to be returned here.

Instead of adjusting this function, could we create a new class / set of functions that handle the distinct behaviour, and then formally deprecate this method, perhaps for removal in 4.0?

2021-10-11 10:58 UTC, pauarge commented on src/class-parsely.php
> -		return $parsely_page;
That is a good point. I have added a deprecation warning, but instead of redirecting users to the new method, I point them to the `construct_parsely_metadata`. That method does return an array instead of printing something, hence, it is more reliable to interact with that data and probably the method customers should have used in the first place.

2021-10-12 09:00 UTC, GaryJones requested changes

2021-10-12 09:00 UTC, GaryJones commented on src/class-parsely.php
> +		return $this->get_options();
Is this returning the right thing? We previously returned the metadata, and this is returning the options?

2021-10-12 11:30 UTC, pauarge commented on src/class-parsely.php
> +		return $this->get_options();
You are right, this is now fixed.

2021-10-13 09:55 UTC, GaryJones approved these changes
I think the DocBlock could be improved, but fine otherwise.

Definitely one to highlight as a breaking change in the changelog.

2021-10-13 09:55 UTC, GaryJones commented on src/class-parsely.php
> +	 * Actually inserts the code for the <meta name='parsely-page'> parameter within the <head></head> tag.
```suggestion
	 * Deprecated. Echoes the metadata into the page, and returns the inserted values.
	 *
	 * To just echo the metadata, use the `insert_page_header_metadata()` method.
	 * To get the metadata to be inserted, use the `construct_parsely_metadata()` method.
```

2021-10-13 10:05 UTC, merged