Remove custom CSS to display version
Parsely/wp-parsely pull request #496
Opened 2021-11-18 15:46 UTC by pauarge

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-11-18 16:06 UTC, sjinks approved these changes

2021-11-19 14:50 UTC, GaryJones commented
I'm not necessarily a fan of this change, but I can disagree and commit. 

If the styles for the help-text class are being removed, can we remove the `<div class="help-text">` elements that wrap the description texts?

2021-11-19 15:04 UTC, sjinks commented
If I am not mistaken, .help-text comes from WP Admin CSS, probably it is worth double-checking...

2021-11-19 15:15 UTC, pauarge commented
@sjinks We're adding that class in a few places in `class-settings-page.php`: https://github.com/Parsely/wp-parsely/blob/d869beeb3e6b4fa76daf47ca82e240d4f147c88e/src/UI/class-settings-page.php#L656

2021-11-25 12:27 UTC, GaryJones requested changes
WP core has:

```css
.form-wrap p, p.description {
    margin: 2px 0 5px;
    color: #646970;
}
.form-wrap p, p.description, p.help, span.description {
    font-size: 13px;
}
```

...so it handles the look of the description text already. All the .help-text did was to narrow the width of the text, but if we look at the core Settings page, then WP lets it run wide as well:
<img width="1420" alt="Screenshot of WP admin settings with long description text" src="https://user-images.githubusercontent.com/88371/143440923-4b0cf02f-c75d-45c2-b9fe-32868c48c757.png">

Since the `.help-text` div's now serve no purpose, I'd like to see them removed from the output.

----

For the version string, I'd prefer to see it left as a `span`, since it still has the same impact is it does now, even with the CSS removed:

With CSS:
<img width="367" alt="light grey version text to the right of the header" src="https://user-images.githubusercontent.com/88371/143441258-ab6cf193-6de3-414d-952d-b8a7292ae0fe.png">
With no CSS:
<img width="367" alt="less light grey version text, just to the right of the header" src="https://user-images.githubusercontent.com/88371/143441289-bef113cd-59b7-45d3-84ba-2cb8df05f2fa.png">

2021-11-28 12:20 UTC, GaryJones approved these changes
Removing the `.help-text` has knock-on effects for the `Important!` message showing, so that would be best to tidy up in another PR. So marking this as ✅.

2021-11-28 12:20 UTC, merged