Release 3.0.4
Parsely/wp-parsely pull request #598
Opened 2022-01-14 17:51 UTC by pauarge

* Moving loading files to named functions

* Moving parsely_initialize_plugin out

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

2022-01-15 11:41 UTC, GaryJones requested changes, later dismissed
What bug does this fix? Why is this needed in a patch release?

2022-01-15 11:41 UTC, GaryJones commented on CHANGELOG.md
> +## [3.0.4] - 2022-01-17
Needs a corresponding entry at the bottom of the file.

2022-01-15 17:50 UTC, pauarge commented
> What bug does this fix? Why is this needed in a patch release? @GaryJones 

We are introducing this change in order to be able to make the changes work in here: https://github.com/Automattic/vip-go-mu-plugins/pull/2808

2022-01-17 10:24 UTC, acicovic approved these changes

2022-01-17 18:07 UTC, merged