Use PHP_EOL instead of "
Parsely/wp-parsely pull request #670
Opened 2022-02-15 08:58 UTC by acicovic

## Description
This is a preview of how the inverse approach of #655 would look like. `composer cs` notifies for bad code, which could be replaced by `PHP_EOL` for every related line in tests. I've left it as is for now, to see if we prefer this approach over #655.

## Motivation and Context
- Being able to make tests pass on windows (fixes #630)

## How Has This Been Tested?
- Integration tests pass on a Windows machine

2022-02-15 09:12 UTC, acicovic commented
Personally I still prefer #655 because it is less verbose, requires less changes and it doesn't have the danger of introducing files with mixed line feeds.

2022-02-15 14:30 UTC, pauarge submitted a review, later dismissed
Great work

2022-02-15 15:07 UTC, GaryJones requested changes
Thanks @acicovic for testing this out.

All things considered, this seems like a lot of changes and hoop-jumping, compared to #655, which was much simpler can cleaner, by being consistent and letting Windows catch up with the rest of the world. The number of web servers and local setups using Windows would only be a small fraction of use cases anyway.

2022-02-15 15:07 UTC, GaryJones commented on tests/Integration/Integrations/GoogleWebStoriesTest.php
> +		echo esc_html( $this::normalize_string( ob_get_clean() ) );
Why does this need to be echo'd? If it's to meet the expectOutputString() above, that that suggests that the `render_amp_analytics_tracker()` call can be removed, which means this isn't actually testing the thing that it's supposed to be testing.

2022-02-15 15:07 UTC, GaryJones commented on tests/Integration/bootstrap.php
> +		echo PHP_EOL . "ERROR: Please check whether the WP_PLUGIN_DIR environment variable is set and set to the correct value. The unit test suite won't be able to run without it." . PHP_EOL;
It's more performant to use commas here (echo three strings), than it is to concat three strings into a single one, and the concat that.

2022-02-15 15:07 UTC, GaryJones commented on tests/Integration/TestCase.php
> +	}
While a clever approach, I'm not a fan. There may be times when we want to check for line-breaks and tabs - for instance, after being normalized `<meta name="parsely-type" content="post	" />` (that's a tab at the end of the content attribute value) would match `<meta name="parsely-type" content="post" />`, and yet the values are technically different, and may be interpreted by the Parse.ly parser as such. Blanket normalizing just in the tests isn't representative of what the actual output from a function or method will be.

2022-02-15 17:01 UTC, acicovic commented on tests/Integration/bootstrap.php
> +		echo PHP_EOL . "ERROR: Please check whether the WP_PLUGIN_DIR environment variable is set and set to the correct value. The unit test suite won't be able to run without it." . PHP_EOL;
Thank you for bringing this into my attention, it makes sense. I've updated this.

2022-02-15 17:01 UTC, acicovic commented on tests/Integration/Integrations/GoogleWebStoriesTest.php
> +		echo esc_html( $this::normalize_string( ob_get_clean() ) );
Not sure what is happening there, will look into this if we decide to go with this PR.

2022-02-15 17:13 UTC, acicovic commented on tests/Integration/TestCase.php
> +	}
You're right of course, and this isn't by any means a perfect solution. Having said that, it should work for most of our testing purposes. I moved the replacements as a parameter so we can have at least a choice of what to remove.

2022-02-15 17:19 UTC, acicovic commented
Concerning which PR to merge, I've expressed my personal preference of #655 here and in that PR. However, I'm probably not the one who has the final say on this, and I don't know if there's a specific process when there are different opinions.

2022-02-16 08:28 UTC, acicovic commented on tests/Integration/Integrations/GoogleWebStoriesTest.php
> +		echo esc_html( $this::normalize_string( ob_get_clean() ) );
Good catch. This was erroneous thinking from my side. I have removed the bad code and adjusted the expected string.

2022-02-16 08:38 UTC, acicovic commented
OK, having said all that, both PRs should be in a ready-to-merge state. I've reopened #655 as well to make our final choice.

2022-02-17 09:32 UTC, pauarge commented
We'll use `\n` as WP Core does.

2022-02-17 09:32 UTC, closed without merging